== ESG: Environmental, Social and Governance

// More headings and sections needed in here.

=== Environment impact and electrical consumption of mining

We are still debating the impact of crypto-assets on the environment due to the high energy consumption implied by blockchain operating model. Companies shouldn‘t overlook it in a context of ESG importance (for more information, see https://www.linkedin.com/pulse/concerned-bitcoin-energy-usage-elon-start-shipping-more-ben-weeks/)


In May, the price of Bitcoin (and other crypto currencies) took a hit. This is nothing new to crypto investors (speculators), but it was seemingly highly correlated to some tweets by one of the world's greatest entrepreneurs and innovators, Elon Musk.

Despite apparently being a relative newcomer to cryptocurrencies, Elon announced Tesla had put $1.5B of worth of Bitcoin on the balance sheet this year, and possibly purchased some more himself (in addition to Dogecoin for his son).

However, it seems only now (after dipping into the coffers for $1.5B) he questioned the energy usage of the bitcoin network.
This seems worrying (as an investor in Tesla) that they would go through with such a purchase without doing due diligence in understanding how bitcoin works.

> Tesla has suspended vehicle purchases using Bitcoin. We are concerned about rapidly increasing use of fossil fuels for Bitcoin mining and transactions, especially coal, which has the worst emissions of any fuel.
>
> We are concerned about rapidly increasing use of fossil fuels for Bitcoin mining and transactions, especially coal, which has the worst emissions of any fuel. 
>
> Cryptocurrency is a good idea on many levels and we believe it has a promising future, but this cannot come at great cost to the environment.
>
> Tesla will not be selling any Bitcoin and we intend to use it for transactions as soon as mining transitions to more sustainable energy. We are also looking at other cryptocurrencies that use <1% of Bitcoin's energy/transaction.
> -- Tesla & Elon Musk 12th May 2021 footnote:[https://twitter.com/elonmusk/status/1392602041025843203]


There was also other FUD (Fear Uncertainty and Doubt) created, with talk about Tesla no longer accepting Bitcoin for payment of Tesla vehicles, going all-in on Doge, and that having run PayPal, he knows more than "us" about how money works.

Some of the typical responses on Twitter where overly hostile (considering Twitter was singing his praises when he got involved with Bitcoin) and in my opinion did nothing to actually try and alleviate his concerns.

There was also understandable concern that Elon was "pumping and dumping" crypto currencies and profiteering off others.
No doubt it is difficult to talk about the technical aspect of digital solutions to money itself when you are the 2nd richest person in the world. footnote:[Forbes Billionaires 2021: The Richest People in the World]
However, Elon has since confirmed Tesla hasn't sold any Bitcoin (although it could be argued he did that to buy more).

With regards to the energy usage of the bitcoin network: Needless to say, yes it is high, but anything of value requires energy - whether that be the creative energy of artists or the effort of labourers, there's no such thing as a free lunch.

Bitcoin's energy use per year is estimated to be less than half that of gold mining and probably the traditional fiat money industry. footnote:[On Bitcoin's Energy Consumption: A Quantitative Approach to a Subjective Question, DocSend, https://docsend.com/view/adwmdeeyfvqwecj2]
However, if the Bitcoin's market capitalisation grew to equal those, it's energy supply would most likely exceed these.
What we can say is, that this energy usage has successfully secured up to $1 trillion worth of value since inception a decade ago. footnote:[Bitcoin price, BTC price index, chart, and info | CoinGecko, https://www.coingecko.com/en/coins/bitcoin]
So that is the price to have secure "sound money".

It also also worthy to mention, that the deflationary nature of sound money (that is, with the capped market supply of 21 million Bitcoins) drives much more eco-friendly behaviour of it's holders that inflationary fiat holders.
If you know that your money will be worth less next year, this drives an unsustainable economy of consumption (best buy now when your purchasing power will be less next year). 
Compared with the deflationary asset such as Bitcoin, where it rewards savers not be be endless consumers.
I am unfamiliar with any studies in this area, but it would be worthwhile of further investigation.

Yes, the energy usage is higher than say the country of Sweden footnote:[Cambridge Bitcoin Electricity Consumption Index (CBECI), https://cbeci.org/cbeci/comparisons], but it's also less than the devices in the US left on standby each year - what value are they giving the world?

As a crypto-miner myself, I can say that the profitability of mining is correlated to the ability to find cheap sources of energy.
Miners are happy to move to use untapped energy resources in remote locations, and in most cases, the cheapest electricity is renewable. This is certainly the case for the likes of Hive Blockchain Technologies footnote:[https://www.linkedin.com/company/hiveblockchain/about/] and Argo Blockchain footnote:[https://www.linkedin.com/company/argoblockchain/].
This is backed up by the fact that it is estimated that 74.1% of the mining energy comes from renewable sources. footnote: [Mining Whitepaper May 2019 Final (With Foreword) (coinfomania.com), https://coinfomania.com/wp-content/uploads/2019/06/Mining-Whitepaper-Coinshares.pdf].
This would be even higher if China, that performs around 65% of the hash power of the network footnote:[Cambridge Bitcoin Electricity Consumption Index (CBECI),https://cbeci.org/mining_map], wasn't predominantly using coal as the primary energy source.

In addition to where their energy comes from, miners could also look to be more eco-friendly with secondary uses of their waste heat (energy) that could be used to further increase profitbility and lessen environmental impact.

In my opinion, and in agreement to Jack Dorsey (CEO of Square and Twitter), crypto mining will drive the cost of energy down and the adoption of renewable energies. It should be noted, that this was something Elon himself apparently agreed with at one point.

> #bitcoin incentivizes renewable energy
> -- Jack Dorsey 21st April 2021 footnote:[https://twitter.com/jack/status/1384903902907314176]


So, if Elon genuinely wants to be part of the solution, what could he do?

* **Provide development resources**. Elon, and his talented team at Tesla and SpaceX, could certainly look to see if the algorithms could be improved upon (as he is apparently doing with the Doge developers). Perhaps some form of "Proof of Renewable" could be built into the hashing code ("code is law" after all), so that only miners that are powered from renewable energy sources are given block rewards (or increased rewards). I don't personally see a way that one electron can be verified as being from a renewable source than another, but perhaps someone else can figure this one out?
* **Assist with decentralising mining away from China**: By incentivising mining away from China, this provides greater security to the network and less reliance on coal as the energy source. NB it can be argued that it is only the pools that are centralised and could easily move hash power to different pools. It is interesting to note that there are over 200,000 decentralised Tesla vehicles on the road (source: By 2023, Tesla Could Have Millions of Cars on the Road (futurism.com)) that are stationary 95% of the time (source: Today’s Cars Are Parked 95% of the Time | Fortune) with advanced CPUs. Although these CPUs are not optimised for mining, perhaps they could be used in relation to optimizing algorithms mentioned above. This could also be assisted with setting up chip manufacturing in the states rather than being dependent on Chinese companies (that get bought up in China first) - this would also help with his Tesla production line bottleneck. Using his "greatest engineering firm in the world" principles to chip manufacturing could also presumably optimize the energy efficiency of these mining devices.
* **Provide miners with cheaper renewable energy sources**: Tesla first announced the roof tile in 2016, but these are still not rolling out worldwide (ref: Elon Musk says Tesla made ‘significant mistakes’ with solar roof project - The Verge). That's 5 years we've been waiting! Quotations that I have received myself for example just use traditional Panasonic panels. By providing the market with true alternatives, supply & demand mechanics tells us this will further drive the affordability of solar and through simple economics and hence drive the adoption of renewables to miners as it is simply the most profitability way to mine - let market dynamics do the rest.
