== Appendix 1: Risk - Reputational

[cols="1,1,1,1"]
|===
|Risk score
|Rank
|Impact
|Probability

|3/5
|4th
|Medium
|High
|===

*_Description_*:

Reputational risk corresponds to a threat or danger to standing of a business/entity or to its name.
There are different type of tokens with some tokens being anonymous or missing proper due diligence and represent a reputational risk.
The adoption of crypto-assets is still in its infancy and hold a bad reputation due to former money laundering activities and excessive electric consumption making them a none eco-friendly investment.

While regulations across the world are in the making, they are still unclear. 
Crypto-assets are considered most of the time as part of none financial risks and hold a reputational risk when using them as treasury tools for the above mentioned elements.

*_Mitigants_*:

The companies should assess the impact to its current reputation relatively to the rest of its activity.
It is also necessary to maintain a good investor relationship and transparency with crypto-assets.
A company could limit itself to best known token such as Bitcoin or Ether.
